# ===========================
# Scope labels
# ===========================

"scope: backend":
  - changed-files:
      - any-glob-to-any-file: "src/**"
      - any-glob-to-any-file: "app/**"
      - any-glob-to-any-file: "services/**"

"scope: infra":
  - changed-files:
      - any-glob-to-any-file: "infra/**"
      - any-glob-to-any-file: "terraform/**"
      - any-glob-to-any-file: ".github/workflows/**"

"scope: docs":
  - changed-files:
      - any-glob-to-any-file: "docs/**"
      - any-glob-to-any-file: "README.md"
      - any-glob-to-any-file: ".github/pull_request_template.md"


# ===========================
# Type-ish labels inferred from files
# (still recommend humans set main type: feat/fix/…)
# ===========================

docs:
  - changed-files:
      - any-glob-to-any-file: "docs/**"
      - any-glob-to-any-file: "README.md"

test:
  - changed-files:
      - any-glob-to-any-file: "tests/**"
      - any-glob-to-any-file: "test/**"
      - any-glob-to-any-file: "**/*.test.*"
      - any-glob-to-any-file: "**/*.spec.*"

build:
  - changed-files:
      - any-glob-to-any-file: ".github/workflows/**"
      - any-glob-to-any-file: "Makefile"
      - any-glob-to-any-file: "package.json"
      - any-glob-to-any-file: "pnpm-lock.yaml"
      - any-glob-to-any-file: "yarn.lock"

infra:
  - changed-files:
      - any-glob-to-any-file: "infra/**"
      - any-glob-to-any-file: "terraform/**"
      - any-glob-to-any-file: "deploy/**"
